### ISSUE TITLE
node start 出错

### ISSUE THREAD

**Issue by wjb2135** [vhtml/webpack-MultiplePage#12]
执行 node start 会出现：
[HPM] Error occurred while trying to proxy request / from localhost:9090 to http://localhost:54999 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

页面打开 显示： Error occured while trying to proxy to: localhost:9090/

**Comment by vhtml** [comment]
这个最近我测试中有遇到过，似乎刷新下浏览器就好了。请最好将本文只作为一篇webpack入门学习的文章来看，毕竟只是基于webpack1.x的，可能会有一些相关插件升级导致的问题出现。
