### ISSUE TITLE
样式中的图片路劲

### ISSUE THREAD

**Issue by zhaotoday** [vhtml/webpack-MultiplePage#2]
我参考你的代码，自己整了下，发现 background-image 的图片路劲只能是绝对路劲。
有没什么好办法？

**Comment by vhtml** [comment]
src/styles/common/grid.css中有使用到背景图片，并且是相对路径。你应该是想说只能使用相对路径吧，这个回答是肯定的，webpack会根据你的配置，将源码中的相对路径最终打包成绝对路径的写法。
