### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by bigmeow** [vhtml/webpack-MultiplePage#5]
1.运行 npm run build 命令后，看你的views目录下的东西还是模板的语法，这表示你的生产环境也要用到supervisor和node 环境么，而不是一个静态资源服务器？
2.不会node，一般我用数据渲染都是ajax请求api，然后用模板渲染引擎把数据渲染成html片段，然后append页面，这里面是如何用node后端模板进行数据渲染呢？
谢谢。

**Comment by vhtml** [comment]
这篇讲的是后端输出模板的方式，关于你的问题可以参考下[第一篇](https://github.com/vhtml/webpack-MultiPage-static)讲的纯静态页面配置。这两篇算是个人学习webpack的笔记吧。其实如果你使用mmvm框架（比如Vue，React等）去开发前端，他们都提供一套工具去生成更高级的webpack配置，非常好用。

**Comment by bigmeow** [comment]
我是打算使用vue  ，不过现在的项目呢，  只是把vue当模板引擎用  ， 不想引入es6和.vue文件，所以打算把你这个稍微改造下，把后台模板渲染弄掉，只用前端模板渲染就行了
