### ISSUE TITLE
.html文件后缀怎么引入公共的CSS和JS呢？

### ISSUE THREAD

**Issue by luchanan** [vhtml/webpack-MultiplePage#9]
是这样的，由于我开发的是多页面，都有一个html文件，这些html文件需要引入共同的js，又不想每次复制到一个新的html。这里看到你在html文件用了include这个是arttemplete语法吗？如果不用，有什么办法解决多页面自动引入公共资源问题呢？

**Comment by vhtml** [comment]
是纯静态多页面吗？是的话，你可以结合上一篇来看[基于webpack的前端工程化开发之多页站点篇（一）](https://github.com/vhtml/webpack-MultiPage-static)

**Comment by claychen6** [comment]
我再试用include，遇到了问题，在index.html中使用{{include './components/header'}}
可总是转换不成功。
还有其他地方，是我没有注意到的吗？
最近一直想把静态开发环境优化一下，望楼主解惑。。。
有其他更好的方法吗？

**Comment by sxei** [comment]
楼主，你的这个`{{include './components/header'}}`误导了多少人啊，估计绝大部分人都以为构建之后就能自动把include文件给编译到HTML文件里面去呢。

**Comment by vhtml** [comment]
真是抱歉，因为之前也考虑过构建之后自动把include文件给编译到HTML文件里面去，但是这样做对于后端模板渲染来说其实没有必要，也不符合后端模板渲染的用户习惯，还增加了一些处理模板的复杂性。这个文中也有提到。
